---
title: "00-EDA"
output: html_notebook
#### Preamble ####
# Purpose: Initial exploratory data analysis of the 2020 stack overflow developer survey obtained from: https://insights.stackoverflow.com/survey/?_ga=2.264336585.777067861.1615819488-1997135835.1608088113
# Author: Morgaine Westin
# Date: 16 March 2021
# Contact: morgaine.westin@mail.utoronto.ca
# License: MIT
# Pre-requisites: 
# - Downloaded stack overflow 2020 survey results and schema csvs must be in inputs/data

---

```{r setup, include = FALSE}
library(tidyverse)
library(here)
library(readr)
library(visdat)
library(janitor)
```

Reading in Data
```{r}
#csv with survey results
survey <- readr::read_csv(here("inputs/data/survey_results_public.csv"))
#survey schema outlining which questions correspond to each column name
schema <- read_csv(here("inputs/data/survey_results_schema.csv"))
glimpse(survey)
head(survey)
```

Checking distribution of Country - Due to the size, we will eventually filter to look only at US data
```{r}
table(survey$Country)

table(survey_clean$EdLevel)
```

Filtering data for US only and selecting variables of potential interest to check for missing data
```{r}
filtered_data <- survey %>%
  filter(Country == "United States") %>%
  select("MainBranch", "Age", "ConvertedComp", "Country", "DevType", "EdLevel", "Employment", "Ethnicity", "Gender",
         "OrgSize", "Sexuality", "SOAccount", "Trans", "UndergradMajor", "WorkWeekHrs", "YearsCode", "YearsCodePro")
head(filtered_data)
summary(filtered_data)

vis_dat(filtered_data)
vis_miss(filtered_data)
sum(is.na(filtered_data))
```

```{r}
filtered_data %>%
  ggplot() + geom_bar(aes(x = MainBranch)) + coord_flip()

filtered_data %>%
  ggplot() + geom_bar(aes(x = Employment)) + coord_flip()
```

```{r}
filtered_data %>%
  ggplot() + geom_bar(aes(x = Gender)) + coord_flip()
```

```{r}
table(survey_clean$Ethnicity)
table(survey_clean2$DevType)
```


```{r}
survey_clean2 %>%
  ggplot() + geom_bar(aes(x = forcats::fct_rev(fct_infreq(Ethnicity)), fill = Gender), stat = "count") + 
  theme(legend.position = "bottom") + coord_flip() + labs(x = "Ethnicity", y = "Respondents")
```
```{r}
#checking characteristics of excluded salaries (less than 10k and greater than 400k) - majority were white males
multiple_eth <- survey %>%
  filter(str_detect(Ethnicity, ";|Biracial|Multiracial"))

survey <- survey %>%
  anti_join(multiple_eth)

survey$Gender <- case_when(str_detect(survey$Gender, "Non-binary, genderqueer, or gender non-conforming")
                                ~ "Non-binary, genderqueer, or gender non-conforming",
                                TRUE ~ survey$Gender)
survey$Gender[survey$Gender == "Woman;Man" ] <- "Non-binary, genderqueer, or gender non-conforming"

survey$Gender <- as.factor(survey$Gender) %>%
  droplevels()

survey <- survey[!is.na(survey$Gender), ] 
survey <- survey[!is.na(survey$Ethnicity), ] 

#Greater than 400k
survey %>%
  filter(Country == "United States", 
         Employment == "Employed full-time",
         ConvertedComp > 400000
  ) %>%
  dplyr::group_by(Ethnicity) %>%
  dplyr::summarise(n()) 

survey %>%
  filter(Country == "United States", 
         Employment == "Employed full-time",
         ConvertedComp > 400000
  ) %>%
  dplyr::group_by(Gender) %>%
  dplyr::summarise(n()) 

#Less than 10k
survey %>%
  filter(Country == "United States", 
         Employment == "Employed full-time",
         ConvertedComp < 10000
  ) %>%
  dplyr::group_by(Ethnicity) %>%
  dplyr::summarise(n()) 

survey %>%
  filter(Country == "United States", 
         Employment == "Employed full-time",
         ConvertedComp < 10000
  ) %>%
  dplyr::group_by(Gender) %>%
  dplyr::summarise(n()) 
  
```

```{r}
 survey_clean %>%
  dplyr::group_by(YearsCodeProNew, Gender) %>%
  dplyr::summarise(median(Salary)) 
  ggplot() +
  geom_bar(aes(x = Gender, y = `median(Salary)`)) 
```



